import 'package:flutter/material.dart';
import 'package:aurogram/core/theme/app_dimensions.dart';

/// Biweekly per-house current-state reading (from skyHouseReadings.houses[N]).
/// Generated by the per_house insight flavor; refreshed every 14 days.
class SkyHouseReading {
  final String? headline;
  final String? reading;
  final String? focus;
  final String? watch;

  const SkyHouseReading({
    this.headline,
    this.reading,
    this.focus,
    this.watch,
  });

  bool get hasContent =>
      (reading != null && reading!.isNotEmpty) ||
      (headline != null && headline!.isNotEmpty);
}

/// Data class for house information shown in the popup.
class HouseInfo {
  final int houseNumber;
  final String zodiacSign;
  final String signLord;
  final List<String> planets;

  /// Static natal interpretation (from houseInterpretations[N].interpretation).
  /// "What this house means based on your birth chart" — never changes.
  final String? interpretation;

  /// Biweekly current-state reading — "what's happening to this house RIGHT NOW".
  final SkyHouseReading? skyReading;

  /// End date of the current 14-day cycle (ISO string, e.g. "2026-05-27").
  final String? cycleEndDate;

  const HouseInfo({
    required this.houseNumber,
    required this.zodiacSign,
    required this.signLord,
    required this.planets,
    this.interpretation,
    this.skyReading,
    this.cycleEndDate,
  });
}

/// Dialog showing both the natal foundation AND the biweekly current-state
/// reading for a tapped house.
class HouseDetailsDialog extends StatelessWidget {
  final HouseInfo info;
  final bool isDark;

  const HouseDetailsDialog({
    super.key,
    required this.info,
    required this.isDark,
  });

  static void show(BuildContext context, HouseInfo info, bool isDark) {
    showDialog(
      context: context,
      builder: (_) => HouseDetailsDialog(info: info, isDark: isDark),
    );
  }

  @override
  Widget build(BuildContext context) {
    final color = _houseColor(info.houseNumber);
    final bg = isDark ? Theme.of(context).colorScheme.surface : Colors.white;
    final hasSky = info.skyReading?.hasContent == true;

    return Dialog(
      backgroundColor: bg,
      shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppDimensions.radiusXl)),
      insetPadding:
          const EdgeInsets.symmetric(horizontal: 24, vertical: 48),
      child: ConstrainedBox(
        constraints: const BoxConstraints(maxWidth: 360, maxHeight: 640),
        child: Padding(
          padding: const EdgeInsets.all(AppDimensions.paddingXl),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              Row(
                children: [
                  _badge(color),
                  const SizedBox(width: AppDimensions.spacingMd),
                  Expanded(child: _title(color)),
                  _closeButton(context),
                ],
              ),
              const SizedBox(height: AppDimensions.spacingLg),

              // Scrollable content area (so longer biweekly readings don't overflow)
              Flexible(
                child: SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Biweekly "right now" reading — primary content when present
                      if (hasSky) ...[
                        _skyReadingBlock(color),
                        const SizedBox(height: AppDimensions.spacingMd),
                      ],

                      // Natal interpretation — the foundation
                      _natalBlock(color, hasSky: hasSky),

                      // Planets in this house
                      if (info.planets.isNotEmpty) ...[
                        const SizedBox(height: AppDimensions.spacingMd),
                        _planetChips(),
                      ],

                      // Cycle date footer
                      if (hasSky && info.cycleEndDate != null) ...[
                        const SizedBox(height: AppDimensions.spacingMd),
                        _cycleFooter(),
                      ],
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // Sky reading block (biweekly current-state)
  // ---------------------------------------------------------------------------

  Widget _skyReadingBlock(Color color) {
    final r = info.skyReading!;
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(AppDimensions.paddingMdLg),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            color.withValues(alpha: isDark ? 0.18 : 0.10),
            color.withValues(alpha: isDark ? 0.08 : 0.04),
          ],
        ),
        borderRadius: BorderRadius.circular(AppDimensions.radiusMd),
        border: Border.all(
          color: color.withValues(alpha: isDark ? 0.35 : 0.25),
          width: 1,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Tag + headline
          Row(
            children: [
              Icon(Icons.auto_awesome, size: 14, color: color),
              const SizedBox(width: 6),
              Text(
                'RIGHT NOW',
                style: TextStyle(
                  fontSize: 10,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 1.2,
                  color: color,
                ),
              ),
            ],
          ),
          if (r.headline != null && r.headline!.isNotEmpty) ...[
            const SizedBox(height: AppDimensions.spacingSm),
            Text(
              r.headline!,
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w700,
                height: 1.3,
                color: isDark ? Colors.white : Colors.black87,
              ),
            ),
          ],
          if (r.reading != null && r.reading!.isNotEmpty) ...[
            const SizedBox(height: AppDimensions.spacingSm),
            Text(
              r.reading!,
              style: TextStyle(
                fontSize: 14,
                height: 1.5,
                color: isDark
                    ? Colors.white.withValues(alpha: 0.88)
                    : Colors.black87,
              ),
            ),
          ],
          if (r.focus != null && r.focus!.isNotEmpty) ...[
            const SizedBox(height: AppDimensions.spacingMd),
            _miniRow(
              icon: Icons.flag_outlined,
              label: 'Focus',
              text: r.focus!,
              accent: Colors.green.shade600,
            ),
          ],
          if (r.watch != null && r.watch!.isNotEmpty) ...[
            const SizedBox(height: AppDimensions.spacingSm),
            _miniRow(
              icon: Icons.warning_amber_rounded,
              label: 'Watch',
              text: r.watch!,
              accent: Colors.orange.shade700,
            ),
          ],
        ],
      ),
    );
  }

  Widget _miniRow({
    required IconData icon,
    required String label,
    required String text,
    required Color accent,
  }) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Icon(icon, size: 14, color: accent),
        const SizedBox(width: 6),
        Text(
          '$label: ',
          style: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w700,
            color: accent,
          ),
        ),
        Expanded(
          child: Text(
            text,
            style: TextStyle(
              fontSize: 12,
              height: 1.45,
              color: isDark
                  ? Colors.white.withValues(alpha: 0.85)
                  : Colors.black87,
            ),
          ),
        ),
      ],
    );
  }

  Widget _cycleFooter() {
    return Row(
      children: [
        Icon(
          Icons.refresh,
          size: 11,
          color: isDark ? Colors.white38 : Colors.black38,
        ),
        const SizedBox(width: 4),
        Text(
          'Refreshes after ${info.cycleEndDate}',
          style: TextStyle(
            fontSize: 10,
            fontStyle: FontStyle.italic,
            color: isDark ? Colors.white38 : Colors.black38,
          ),
        ),
      ],
    );
  }

  // ---------------------------------------------------------------------------
  // Natal block (foundation)
  // ---------------------------------------------------------------------------

  Widget _natalBlock(Color color, {required bool hasSky}) {
    final text = info.interpretation ??
        (hasSky
            ? null
            : 'Sync your birth chart to unlock personalized insights.');

    if (text == null) return const SizedBox.shrink();

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(AppDimensions.paddingMdLg),
      decoration: BoxDecoration(
        color: isDark
            ? Colors.white.withValues(alpha: 0.04)
            : color.withValues(alpha: 0.04),
        borderRadius: BorderRadius.circular(AppDimensions.radiusMd),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (hasSky) ...[
            Row(
              children: [
                Icon(
                  Icons.account_tree_outlined,
                  size: 12,
                  color: isDark ? Colors.white54 : Colors.black54,
                ),
                const SizedBox(width: 4),
                Text(
                  'YOUR NATAL FOUNDATION',
                  style: TextStyle(
                    fontSize: 9,
                    fontWeight: FontWeight.w700,
                    letterSpacing: 1.1,
                    color: isDark ? Colors.white54 : Colors.black54,
                  ),
                ),
              ],
            ),
            const SizedBox(height: AppDimensions.spacingSm),
          ],
          Text(
            text,
            style: TextStyle(
              fontSize: 13,
              height: 1.5,
              color: isDark
                  ? Colors.white.withValues(alpha: 0.78)
                  : Colors.black.withValues(alpha: 0.75),
            ),
          ),
        ],
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // Header pieces
  // ---------------------------------------------------------------------------

  Widget _badge(Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(
          horizontal: AppDimensions.paddingMd,
          vertical: AppDimensions.paddingSm),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.15),
        borderRadius: BorderRadius.circular(AppDimensions.radiusMdSm),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            'Your',
            style: TextStyle(
              fontSize: 9,
              fontWeight: FontWeight.w600,
              color: color.withValues(alpha: 0.8),
              height: 1,
            ),
          ),
          const SizedBox(height: AppDimensions.spacingXxs),
          Text(
            _ordinal(info.houseNumber),
            style: TextStyle(
              fontSize: 15,
              fontWeight: FontWeight.bold,
              color: color,
              height: 1,
            ),
          ),
          const SizedBox(height: AppDimensions.spacingXxs),
          Text(
            'House',
            style: TextStyle(
              fontSize: 10,
              fontWeight: FontWeight.w600,
              color: color.withValues(alpha: 0.8),
              height: 1,
            ),
          ),
        ],
      ),
    );
  }

  Widget _title(Color color) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          _houseName(info.houseNumber),
          style: TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.bold,
            color: isDark ? Colors.white : Colors.black87,
          ),
        ),
        Text(
          '${info.zodiacSign} • ${info.signLord}',
          style: TextStyle(
              fontSize: 12, color: color, fontWeight: FontWeight.w600),
        ),
      ],
    );
  }

  Widget _closeButton(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pop(context),
      child: Icon(
        Icons.close,
        size: 20,
        color: isDark ? Colors.white54 : Colors.black38,
      ),
    );
  }

  Widget _planetChips() {
    return Wrap(
      spacing: 6,
      runSpacing: 6,
      children: info.planets.map((p) {
        return Container(
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
          decoration: BoxDecoration(
            color: isDark
                ? Colors.amber.withValues(alpha: 0.15)
                : Colors.orange.withValues(alpha: 0.1),
            borderRadius: BorderRadius.circular(AppDimensions.radiusLg),
          ),
          child: Text(
            '${_planetSymbol(p)} $p',
            style: TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.w600,
              color: isDark
                  ? Colors.amber.shade300
                  : Colors.deepOrange.shade700,
            ),
          ),
        );
      }).toList(),
    );
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  String _ordinal(int n) {
    if (n >= 11 && n <= 13) return '${n}th';
    switch (n % 10) {
      case 1:
        return '${n}st';
      case 2:
        return '${n}nd';
      case 3:
        return '${n}rd';
      default:
        return '${n}th';
    }
  }

  Color _houseColor(int h) {
    if ([1, 4, 7, 10].contains(h)) return Colors.amber.shade700;
    if ([5, 9].contains(h)) return Colors.green.shade600;
    if ([6, 8, 12].contains(h)) return Colors.red.shade400;
    if ([3, 11].contains(h)) return Colors.blue.shade500;
    return Colors.purple.shade400;
  }

  String _houseName(int h) {
    const names = {
      1: 'Self & Identity',
      2: 'Wealth & Values',
      3: 'Courage & Siblings',
      4: 'Home & Mother',
      5: 'Children & Creativity',
      6: 'Health & Service',
      7: 'Marriage & Partnership',
      8: 'Transformation',
      9: 'Fortune & Dharma',
      10: 'Career & Status',
      11: 'Gains & Aspirations',
      12: 'Spirituality & Liberation',
    };
    return names[h] ?? 'House $h';
  }

  String _planetSymbol(String name) {
    final l = name.toLowerCase();
    if (l.contains('sun')) return '☉';
    if (l.contains('moon')) return '☽';
    if (l.contains('mars')) return '♂';
    if (l.contains('mercury')) return '☿';
    if (l.contains('jupiter')) return '♃';
    if (l.contains('venus')) return '♀';
    if (l.contains('saturn')) return '♄';
    if (l.contains('rahu')) return '☊';
    if (l.contains('ketu')) return '☋';
    return '•';
  }
}

/// Helpers for house calculations
class HouseSignifications {
  static String getSignForHouse(int houseNumber, int lagnaSignIndex) {
    const signs = [
      'Aries',
      'Taurus',
      'Gemini',
      'Cancer',
      'Leo',
      'Virgo',
      'Libra',
      'Scorpio',
      'Sagittarius',
      'Capricorn',
      'Aquarius',
      'Pisces'
    ];
    return signs[(lagnaSignIndex + houseNumber - 1) % 12];
  }

  static String getSignLord(String sign) {
    const lords = {
      'Aries': 'Mars',
      'Taurus': 'Venus',
      'Gemini': 'Mercury',
      'Cancer': 'Moon',
      'Leo': 'Sun',
      'Virgo': 'Mercury',
      'Libra': 'Venus',
      'Scorpio': 'Mars',
      'Sagittarius': 'Jupiter',
      'Capricorn': 'Saturn',
      'Aquarius': 'Saturn',
      'Pisces': 'Jupiter',
    };
    return lords[sign] ?? 'Unknown';
  }
}
