// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6iwAv1s2c-94m0NlbSZF-gFTz7lx1n0U',
    appId: '1:735015361682:web:41967cb0b981c01d645a4b',
    messagingSenderId: '735015361682',
    projectId: 'ty-dev-516d7',
    authDomain: 'ty-dev-516d7.firebaseapp.com',
    storageBucket: 'ty-dev-516d7.appspot.com',
    measurementId: 'G-1MKY2SL7H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2IyGmDVyjJGM2JsXx3wRY-D8wVo1xC84',
    appId: '1:735015361682:android:027041218632a03b645a4b',
    messagingSenderId: '735015361682',
    projectId: 'ty-dev-516d7',
    storageBucket: 'ty-dev-516d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nnU5r74OZAq3MDmOGEOXpKA9SpJF5_g',
    appId: '1:735015361682:ios:42ba864cb814d372645a4b',
    messagingSenderId: '735015361682',
    projectId: 'ty-dev-516d7',
    storageBucket: 'ty-dev-516d7.appspot.com',
    androidClientId: '735015361682-5ghlk3lgnrl6u265lrocg87nvmk65jgm.apps.googleusercontent.com',
    iosClientId: '735015361682-q0r1bvv9ok98eo1hkc6bekkc5oi14mhe.apps.googleusercontent.com',
    iosBundleId: 'com.canay.yantra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0nnU5r74OZAq3MDmOGEOXpKA9SpJF5_g',
    appId: '1:735015361682:ios:1092aa0221a50d0d645a4b',
    messagingSenderId: '735015361682',
    projectId: 'ty-dev-516d7',
    storageBucket: 'ty-dev-516d7.appspot.com',
    androidClientId: '735015361682-5ghlk3lgnrl6u265lrocg87nvmk65jgm.apps.googleusercontent.com',
    iosClientId: '735015361682-f9uhrtqmbbkub0s4l13h3og2vusc10t9.apps.googleusercontent.com',
    iosBundleId: 'com.canay.tribes',
  );
}
