#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# build-web.sh  –  Build Flutter web with post-build optimizations
#
# Usage:  ./scripts/build-web.sh [--deploy]
#
# What it does:
#   1. flutter build web --release
#   2. Patches flutter_bootstrap.js:
#      - Removes serviceWorkerSettings (prevents Flutter SW race)
#      - Injects loading-screen callback (onEntrypointLoaded)
#   3. Removes flutter_service_worker.js (dead weight — we use our own)
#   4. Optionally deploys to Firebase Hosting (--deploy flag)
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

DEPLOY=false
[[ "${1:-}" == "--deploy" ]] && DEPLOY=true

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build/web"
BOOTSTRAP="$BUILD_DIR/flutter_bootstrap.js"

echo "▸ Building Flutter web (release)..."
cd "$PROJECT_ROOT"
# FLUTTER_BUILD_ARGS lets callers pass extra flags to `flutter build web`,
# e.g. FLUTTER_BUILD_ARGS=--no-pub on machines that can't reach pub.dev.
flutter build web --release --no-wasm-dry-run ${FLUTTER_BUILD_ARGS:-}

# Verify bootstrap exists
if [[ ! -f "$BOOTSTRAP" ]]; then
  echo "✘ flutter_bootstrap.js not found in build output" >&2
  exit 1
fi

echo "▸ Patching flutter_bootstrap.js..."

# The generated bootstrap ends with an auto-call like:
#
#   _flutter.loader.load({
#     serviceWorkerSettings: {
#       serviceWorkerVersion: "XXXXXXXXXX" /* ... */
#     }
#   });
#
# We replace it with a call that:
#   a) Skips service worker (our firebase-messaging-sw.js handles caching)
#   b) Adds onEntrypointLoaded to dismiss the loading screen
#
# Strategy: match the final _flutter.loader.load({...}); block at end of file.
# We use multiple patterns to handle minified vs pretty-printed Flutter output.

python3 -c "
import re, sys

path = '$BOOTSTRAP'
with open(path, 'r') as f:
    src = f.read()

replacement = '''_flutter.loader.load({
  onEntrypointLoaded: function(engineInitializer) {
    engineInitializer.initializeEngine().then(function(appRunner) {
      document.body.classList.add(\"flutter-loaded\");
      appRunner.runApp();
    });
  }
});'''

# Strategy: find and replace the LAST _flutter.loader.load({...}); block in the
# file using rfind — immune to any preceding occurrences in the minified engine code.
MARKER = '_flutter.loader.load({'
last_idx = src.rfind(MARKER)
if last_idx == -1:
    print('✘  Could not find _flutter.loader.load({ in file', file=sys.stderr)
    sys.exit(1)

end_idx = src.find('});', last_idx)
if end_idx == -1:
    print('✘  Could not find closing }); after last _flutter.loader.load({', file=sys.stderr)
    sys.exit(1)

result = src[:last_idx] + replacement + src[end_idx + 3:]

if result == src:
    print('✘  Patch produced no change — file may already be patched or format unexpected', file=sys.stderr)
    sys.exit(1)

print('✔  Patched: replaced last _flutter.loader.load({...}); with onEntrypointLoaded callback')

# Sanity check: onEntrypointLoaded must be present, and the LAST occurrence
# of _flutter.loader.load must NOT contain serviceWorkerSettings.
if 'onEntrypointLoaded' not in result:
    print('✘  Patch applied but onEntrypointLoaded not found in output!', file=sys.stderr)
    sys.exit(1)

tail = result[result.rfind('_flutter.loader.load({'):]
if 'serviceWorkerSettings' in tail:
    print('✘  Patch applied but serviceWorkerSettings still present in output!', file=sys.stderr)
    sys.exit(1)

with open(path, 'w') as f:
    f.write(result)
"

# Remove flutter_service_worker.js — it's generated by the build but we
# don't use it (firebase-messaging-sw.js handles all caching/push).
# Keeping it around means it gets deployed and could be accidentally registered.
if [[ -f "$BUILD_DIR/flutter_service_worker.js" ]]; then
  rm "$BUILD_DIR/flutter_service_worker.js"
  echo "✔  Removed unused flutter_service_worker.js"
fi

echo "✔  Build complete: $BUILD_DIR"

if $DEPLOY; then
  echo "▸ Deploying to Firebase Hosting..."
  firebase deploy --only hosting
  echo "✔  Deployed!"
fi
