#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# build-web.sh  –  Build Flutter web with post-build optimizations
#
# Usage:  ./scripts/build-web.sh [--deploy]
#
# What it does:
#   1. flutter build web --release
#   2. Patches flutter_bootstrap.js:
#      - Removes serviceWorkerSettings (prevents Flutter SW race)
#      - Injects loading-screen callback (onEntrypointLoaded)
#   3. Removes flutter_service_worker.js (dead weight — we use our own)
#   4. Optionally deploys to Firebase Hosting (--deploy flag)
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

DEPLOY=false
[[ "${1:-}" == "--deploy" ]] && DEPLOY=true

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build/web"
BOOTSTRAP="$BUILD_DIR/flutter_bootstrap.js"

echo "▸ Building Flutter web (release)..."
cd "$PROJECT_ROOT"
flutter build web --release --no-wasm-dry-run

# Verify bootstrap exists
if [[ ! -f "$BOOTSTRAP" ]]; then
  echo "✘ flutter_bootstrap.js not found in build output" >&2
  exit 1
fi

echo "▸ Patching flutter_bootstrap.js..."

# The generated bootstrap ends with an auto-call like:
#
#   _flutter.loader.load({
#     serviceWorkerSettings: {
#       serviceWorkerVersion: "XXXXXXXXXX" /* ... */
#     }
#   });
#
# We replace it with a call that:
#   a) Skips service worker (our firebase-messaging-sw.js handles caching)
#   b) Adds onEntrypointLoaded to dismiss the loading screen
#
# The regex matches the final _flutter.loader.load({...}); block at the end.

python3 -c "
import re, sys

path = '$BOOTSTRAP'
with open(path, 'r') as f:
    src = f.read()

# Match the final _flutter.loader.load(...); call
# It can span multiple lines and includes serviceWorkerSettings
pattern = r'_flutter\.loader\.load\(\{[^}]*serviceWorkerSettings[^)]*\}\);'
replacement = '''_flutter.loader.load({
  onEntrypointLoaded: function(engineInitializer) {
    engineInitializer.initializeEngine().then(function(appRunner) {
      document.body.classList.add('flutter-loaded');
      appRunner.runApp();
    });
  }
});'''

result = re.sub(pattern, replacement, src, count=1, flags=re.DOTALL)

if result == src:
    print('⚠  Could not find serviceWorkerSettings block — bootstrap may have changed format', file=sys.stderr)
    print('   Attempting fallback: replace entire load() call...', file=sys.stderr)
    # Fallback: match any _flutter.loader.load(...) at end of file
    pattern2 = r'_flutter\.loader\.load\(\{[^;]*\}\);'
    result = re.sub(pattern2, replacement, src, count=1, flags=re.DOTALL)

if result == src:
    print('✘  Failed to patch flutter_bootstrap.js', file=sys.stderr)
    sys.exit(1)

with open(path, 'w') as f:
    f.write(result)

print('✔  Patched: removed serviceWorkerSettings, added loading-screen callback')
"

# Remove flutter_service_worker.js — it's generated by the build but we
# don't use it (firebase-messaging-sw.js handles all caching/push).
# Keeping it around means it gets deployed and could be accidentally registered.
if [[ -f "$BUILD_DIR/flutter_service_worker.js" ]]; then
  rm "$BUILD_DIR/flutter_service_worker.js"
  echo "✔  Removed unused flutter_service_worker.js"
fi

echo "✔  Build complete: $BUILD_DIR"

if $DEPLOY; then
  echo "▸ Deploying to Firebase Hosting..."
  firebase deploy --only hosting
  echo "✔  Deployed!"
fi
